"""File storage for uploads, internal artifacts and outputs. Paths are always job-scoped and
generated by the server (users/{uid}/jobs/{jobId}/...); user file names are display metadata only."""

import shutil
from datetime import timedelta
from pathlib import Path
from typing import Protocol


class FileStore(Protocol):
    def put(self, path: str, data: bytes, content_type: str) -> None: ...
    def get(self, path: str) -> bytes: ...
    def exists(self, path: str) -> bool: ...
    def delete(self, path: str) -> None: ...
    def delete_prefix(self, prefix: str) -> None: ...
    def local_path(self, path: str) -> Path | None: ...
    def signed_url(self, path: str, download_name: str) -> str | None: ...


def _safe(path: str) -> str:
    parts = [p for p in path.split("/") if p]
    if not parts or any(p in (".", "..") or "\\" in p for p in parts):
        raise ValueError("unsafe storage path")
    return "/".join(parts)


class LocalFileStore:
    def __init__(self, root: Path):
        self._root = (root / "files").resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _full(self, path: str) -> Path:
        full = (self._root / _safe(path)).resolve()
        if self._root not in full.parents:
            raise ValueError("path escapes storage root")
        return full

    def put(self, path: str, data: bytes, content_type: str) -> None:
        full = self._full(path)
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_bytes(data)

    def get(self, path: str) -> bytes:
        return self._full(path).read_bytes()

    def exists(self, path: str) -> bool:
        return self._full(path).exists()

    def delete(self, path: str) -> None:
        self._full(path).unlink(missing_ok=True)

    def delete_prefix(self, prefix: str) -> None:
        shutil.rmtree(self._full(prefix), ignore_errors=True)

    def local_path(self, path: str) -> Path | None:
        return self._full(path)

    def signed_url(self, path: str, download_name: str) -> str | None:
        return None  # local downloads are streamed by the API


class GcsFileStore:
    def __init__(self, bucket: str, project: str | None):
        from google.cloud import storage

        self._bucket = storage.Client(project=project).bucket(bucket)

    def put(self, path: str, data: bytes, content_type: str) -> None:
        self._bucket.blob(_safe(path)).upload_from_string(data, content_type=content_type)

    def get(self, path: str) -> bytes:
        return self._bucket.blob(_safe(path)).download_as_bytes()

    def exists(self, path: str) -> bool:
        return self._bucket.blob(_safe(path)).exists()

    def delete(self, path: str) -> None:
        from google.api_core.exceptions import NotFound

        try:
            self._bucket.blob(_safe(path)).delete()
        except NotFound:
            pass  # already gone: deletion is idempotent

    def delete_prefix(self, prefix: str) -> None:
        for blob in self._bucket.list_blobs(prefix=_safe(prefix) + "/"):
            blob.delete()

    def local_path(self, path: str) -> Path | None:
        return None

    def signed_url(self, path: str, download_name: str) -> str | None:
        # Cloud Run credentials hold no private key, so signing goes through the IAM signBlob API
        # (requires roles/iam.serviceAccountTokenCreator on the runtime service account).
        import google.auth
        from google.auth.transport.requests import Request

        credentials, _ = google.auth.default()
        credentials.refresh(Request())
        safe_name = download_name.replace('"', "").encode("ascii", "ignore").decode() or "paperaid.docx"
        return self._bucket.blob(_safe(path)).generate_signed_url(
            version="v4",
            expiration=timedelta(minutes=10),
            method="GET",
            response_disposition=f'attachment; filename="{safe_name}"',
            service_account_email=getattr(credentials, "service_account_email", None),
            access_token=credentials.token,
        )
